// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String rtdbUrl = 'https://omega-call-default-rtdb.firebaseio.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVPM49KmpDEUZV_ubSIyd2kP1F10Y5l1o',
    appId: '1:322375352930:web:ee907fce6690a0f3c2073b',
    messagingSenderId: '322375352930',
    projectId: 'omega-call',
    authDomain: 'omega-call.firebaseapp.com',
    storageBucket: 'omega-call.firebasestorage.app',
    databaseURL: rtdbUrl,
    measurementId: 'G-TD9Z5H1CXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_G0rADbyWby2BV9o4J8VFMMl_yh90teA',
    appId: '1:322375352930:android:fb483ff990ec964cc2073b',
    messagingSenderId: '322375352930',
    projectId: 'omega-call',
    databaseURL: rtdbUrl,
    storageBucket: 'omega-call.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7Xj0TcNLfUNFICxqGqPFzAeDMZ3VmfU',
    appId: '1:322375352930:ios:849fa41bf9cdee43c2073b',
    messagingSenderId: '322375352930',
    projectId: 'omega-call',
    databaseURL: rtdbUrl,
    storageBucket: 'omega-call.firebasestorage.app',
    iosBundleId: 'com.omegacall.app.omegaCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV7Xj0TcNLfUNFICxqGqPFzAeDMZ3VmfU',
    appId: '1:322375352930:ios:849fa41bf9cdee43c2073b',
    messagingSenderId: '322375352930',
    projectId: 'omega-call',
    databaseURL: rtdbUrl,
    storageBucket: 'omega-call.firebasestorage.app',
    iosBundleId: 'com.omegacall.app.omegaCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVPM49KmpDEUZV_ubSIyd2kP1F10Y5l1o',
    appId: '1:322375352930:web:7ae4dd10d31f9d98c2073b',
    messagingSenderId: '322375352930',
    projectId: 'omega-call',
    authDomain: 'omega-call.firebaseapp.com',
    databaseURL: rtdbUrl,
    storageBucket: 'omega-call.firebasestorage.app',
    measurementId: 'G-34EXXSY8QF',
  );
}
